FROM node:20-alpine AS builder
RUN corepack enable && corepack prepare pnpm@9 --activate
WORKDIR /src
ARG VITE_API_TARGET
ENV VITE_API_TARGET=$VITE_API_TARGET
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
COPY packages/web/package.json packages/web/package.json
COPY packages/core/package.json packages/core/package.json
RUN pnpm install --prod=false
COPY . .
RUN pnpm --filter @secondplanet/core build || true
RUN pnpm --filter @secondplanet/web run build

FROM nginx:alpine
COPY --from=builder /src/packages/web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
